Repository nuwave/lighthouse, pull requests merged in 2018-12, with the labels that each got.

#464 Add the @cache directive to the documentation
  docs/2.6/api-reference/directives.md
  docs/master/api-reference/directives.md
Labels: docs

#517 Bump webonyx/graphql-php to ^0.13 and php to >= 7.1
  .travis.yml
  composer.json
  src/Console/stubs/scalar.stub
  src/Exceptions/GenericException.php
  src/Execution/ExtensionErrorHandler.php
  src/Schema/Types/Scalars/Date.php
  src/Schema/Types/Scalars/DateTime.php
  src/Schema/Values/FieldValue.php
  src/Subscriptions/Subscriber.php
  src/Support/helpers.php
  tests/Integration/Subscriptions/HandlesSubscribers.php
  tests/Unit/Schema/Directives/Args/RulesDirectiveTest.php
  tests/Unit/Schema/Extensions/DeferExtensionTest.php
  tests/Utils/Scalars/Email.php
Labels: enhancement, v3.x

#519 Prevent name conflict between argument names and non-relation methods when executing nested mutations
  docs/master/guides/relationships.md
  src/Execution/MutationExecutor.php
  tests/Integration/Schema/Directives/Fields/CreateDirectiveTest.php
  tests/database/migrations/2018_02_28_000003_create_testbench_tasks_table.php
Labels: bug

#431 Allow user to be guest when using the @can directive
  docs/master/api-reference/directives.md
  src/Schema/Directives/Fields/CanDirective.php
  tests/Unit/Schema/Directives/Fields/CanDirectiveTest.php
  tests/Utils/Policies/UserPolicy.php
Labels: enhancement

#520 Replace `DirectiveRegistry` with `DirectiveFactory` to lazy load directives
  config/config.php
  docs/master/getting-started/configuration.md
  docs/master/guides/plugin-development.md
  src/Events/RegisteringDirectiveBaseNamespaces.php
  src/Providers/LighthouseServiceProvider.php
  src/Schema/AST/ASTBuilder.php
  src/Schema/DirectiveRegistry.php
  src/Schema/Factories/ArgumentFactory.php
  src/Schema/Factories/DirectiveFactory.php
  src/Schema/Factories/FieldFactory.php
  src/Schema/Factories/NodeFactory.php
  tests/Integration/Events/RegisteringDirectiveBaseNamespacesTest.php
  tests/Unit/Schema/DirectiveRegistryTest.php
  tests/Unit/Schema/Factories/DirectiveFactoryTest.php
Labels: enhancement
