Repository nuwave/lighthouse, pull requests merged in 2019-05, with the labels that each got.

#774 Allow Query input argument using `@spread` to be optional
  CHANGELOG.md
  src/Schema/Factories/FieldFactory.php
  tests/Unit/Schema/Directives/SpreadDirectiveTest.php
Labels: bug

#779 Document usage of native PHP types, add convencience wrapper for bensampo/laravel-enum
  CHANGELOG.md
  composer.json
  docs/master/getting-started/migrating-to-lighthouse.md
  docs/master/guides/native-php-types.md
  docs/master/sidebar.js
  docs/master/the-basics/types.md
  src/Schema/Types/LaravelEnumType.php
  tests/Unit/Schema/Types/LaravelEnumTypeTest.php
  tests/Utils/LaravelEnums/UserType.php
  tests/Utils/Models/User.php
  tests/database/migrations/2018_02_28_000002_create_testbench_users_table.php
Labels: docs, enhancement

#753 Flexible client side querying through `@whereConstraints` directive
  CHANGELOG.md
  composer.json
  docs/master/api-reference/directives.md
  src/Schema/AST/ASTBuilder.php
  src/WhereConstraints/WhereConstraintsDirective.php
  src/WhereConstraints/WhereConstraintsServiceProvider.php
  tests/Integration/WhereConstraints/WhereConstraintsDirectiveTest.php
Labels: enhancement

#784 Directive arguments in docs
  docs/master/api-reference/directives.md
Labels: docs

#786 Add compatibility layer to allow @middleware to support Lumen
  CHANGELOG.md
  composer.json
  src/LighthouseServiceProvider.php
  src/Schema/Directives/MiddlewareDirective.php
  src/Support/Compatibility/LaravelMiddlewareAdapter.php
  src/Support/Compatibility/LumenMiddlewareAdapter.php
  src/Support/Compatibility/MiddlewareAdapter.php
  src/Support/Utils.php
Labels: enhancement, lumen

#800 Fix querying for falsy values through `@whereConstraints`
  CHANGELOG.md
  src/WhereConstraints/WhereConstraintsDirective.php
  tests/Integration/WhereConstraints/WhereConstraintsDirectiveTest.php
Labels: bug

#801 Add config option `cache.ttl` to control expiration time of schema cache
  CHANGELOG.md
  config/config.php
  docs/master/getting-started/configuration.md
  src/GraphQL.php
Labels: enhancement

#807 Typo: Rename model Users to User
  docs/3.6/getting-started/tutorial.md
  docs/master/getting-started/tutorial.md
Labels: docs

#812 Support custom rule classes in `@rules` and `@rulesForArray`
  CHANGELOG.md
  docs/master/api-reference/directives.md
  src/Schema/Directives/RulesDirective.php
  src/Schema/Directives/RulesForArrayDirective.php
  tests/Unit/Schema/Directives/RulesDirectiveTest.php
  tests/Utils/Rules/FooBarRule.php
Labels: enhancement

#668 New structure for docs
  docker-compose.yml
  docs/.vuepress/versions.json
  docs/master/api-reference/commands.md
  docs/master/api-reference/directives.md
  docs/master/api-reference/scalars.md
  docs/master/custom-directives/argument-directives.md
  docs/master/custom-directives/field-directives.md
  docs/master/custom-directives/getting-started.md
  docs/master/custom-directives/node-directives.md
  docs/master/digging-deeper/adding-types-programmatically.md
  docs/master/digging-deeper/error-handling.md
  docs/master/digging-deeper/extending-lighthouse.md
  docs/master/digging-deeper/file-uploads.md
  docs/master/digging-deeper/relay.md
  docs/master/digging-deeper/schema-organisation.md
  docs/master/eloquent/getting-started.md
  docs/master/eloquent/nested-mutations.md
  docs/master/eloquent/relationships.md
  docs/master/extensions/subscriptions.md
  docs/master/getting-started/installation.md
  docs/master/getting-started/migrating-to-lighthouse.md
  docs/master/getting-started/tutorial.md
  docs/master/performance/deferred.md
  docs/master/performance/n-plus-one.md
  docs/master/performance/schema-caching.md
  docs/master/performance/server-configuration.md
  docs/master/performance/tracing.md
  docs/master/security/authentication.md
  docs/master/security/authorization.md
  docs/master/security/resource-exhaustion.md
  docs/master/security/validation.md
  docs/master/sidebar.js
  docs/master/subscriptions/client-implementations.md
  docs/master/subscriptions/defining-fields.md
  docs/master/subscriptions/filtering-subscriptions.md
  docs/master/subscriptions/getting-started.md
  docs/master/subscriptions/trigger-subscriptions.md
  docs/master/testing/phpunit.md
  docs/master/the-basics/directives.md
  docs/master/the-basics/fields.md
  docs/master/the-basics/types.md
  docs/pages/resources.md
  src/Console/InterfaceCommand.php
  src/Console/PrintSchemaCommand.php
  src/Console/ScalarCommand.php
  src/Console/UnionCommand.php
  src/Console/ValidateSchemaCommand.php
  tests/Integration/GraphQLTest.php
Labels: docs

#816 Run benchmarks in travis
  .travis.yml
Labels: performance

#768 Improve performance by lazily unserializing and loading types from the schema
  CHANGELOG.md
  composer.json
  config/config.php
  docs/master/api-reference/directives.md
  docs/master/custom-directives/argument-directives.md
  docs/master/custom-directives/field-directives.md
  docs/master/custom-directives/node-directives.md
  docs/master/custom-directives/type-directives.md
  docs/master/eloquent/nested-mutations.md
  docs/master/security/authentication.md
  docs/master/sidebar.js
  src/Defer/Defer.php
  src/GraphQL.php
  src/Pagination/PaginationManipulator.php
  src/Schema/AST/ASTBuilder.php
  src/Schema/AST/ASTHelper.php
  src/Schema/AST/DocumentAST.php
  src/Schema/Directives/BaseDirective.php
  src/Schema/Directives/CacheDirective.php
  src/Schema/Directives/GroupDirective.php
  src/Schema/Directives/MiddlewareDirective.php
  src/Schema/Directives/ModelDirective.php
  src/Schema/Directives/NamespaceDirective.php
  src/Schema/Directives/NodeDirective.php
  src/Schema/Directives/OrderByDirective.php
  src/Schema/Directives/PaginateDirective.php
  src/Schema/Directives/RelationDirective.php
  src/Schema/Factories/ClientDirectiveFactory.php
  src/Schema/Factories/DirectiveFactory.php
  src/Schema/Factories/NodeFactory.php
  src/Schema/SchemaBuilder.php
  src/Schema/TypeRegistry.php
  src/Schema/Values/FieldValue.php
  src/Schema/Values/TypeValue.php
  src/Support/Contracts/ArgManipulator.php
  src/Support/Contracts/FieldManipulator.php
  src/Support/Contracts/NodeManipulator.php
  src/Support/Contracts/NodeResolver.php
  src/Support/Contracts/TypeExtensionManipulator.php
  src/Support/Contracts/TypeManipulator.php
  src/Support/Contracts/TypeMiddleware.php
  src/Support/Contracts/TypeResolver.php
  src/Tracing/Tracing.php
  src/WhereConstraints/WhereConstraintsServiceProvider.php
  tests/Integration/IntrospectionTest.php
  tests/Integration/Schema/Directives/PaginateDirectiveTest.php
  tests/Integration/Schema/Types/InterfaceTest.php
  tests/TestSchemaProvider.php
  tests/Unit/Events/ManipulateASTTest.php
  tests/Unit/Schema/AST/ASTBuilderTest.php
  tests/Unit/Schema/AST/DocumentASTTest.php
  tests/Unit/Schema/Directives/GroupDirectiveTest.php
  tests/Unit/Schema/Directives/MiddlewareDirectiveTest.php
  tests/Unit/Schema/Directives/NamespaceDirectiveTest.php
  tests/Unit/Schema/Directives/PaginateDirectiveTest.php
  tests/Unit/Schema/ResolverProviderTest.php
  tests/Unit/Schema/TypeRegistryTest.php
  tests/Utils/Queries/Foo.php
  tests/Utils/QueriesSecondary/Baz.php
  tests/Utils/QueriesSecondary/Foo.php
Labels: performance
