Repository nuwave/lighthouse, pull requests merged in 2019-03, with the labels that each got.

#628 Add support for file uploads
  assets/default-schema.graphql
  docs/master/api-reference/scalars.md
  docs/master/guides/file-uploads.md
  docs/master/sidebar.js
  docs/master/the-basics/types.md
  src/Execution/BaseRequest.php
  src/Execution/GraphQLRequest.php
  src/Execution/LighthouseRequest.php
  src/Execution/MultipartFormRequest.php
  src/LighthouseServiceProvider.php
  src/Schema/Directives/Fields/PaginationManipulator.php
  src/Schema/Types/Scalars/Upload.php
  src/Support/Http/Controllers/GraphQLController.php
  tests/Integration/GraphQLTest.php
  tests/TestCase.php
  tests/Unit/Schema/Types/Scalars/UploadTest.php
  tests/Utils/Mutations/Upload.php
Labels: enhancement

#569 Add config & arg for @paginate to limit use of count
  config/config.php
  docs/master/api-reference/directives.md
  docs/master/getting-started/configuration.md
  src/Execution/DataLoader/RelationBatchLoader.php
  src/Execution/Utils/Pagination.php
  src/Schema/Directives/Fields/PaginateDirective.php
  src/Schema/Directives/Fields/PaginationManipulator.php
  src/Schema/Directives/Fields/RelationDirective.php
  tests/Integration/Schema/Directives/Fields/HasManyDirectiveTest.php
  tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php
  tests/Unit/Schema/Directives/Fields/PaginateDirectiveTest.php
Labels: enhancement

#659 Add @orderBy argument directive
  docs/master/api-reference/directives.md
  src/Schema/AST/ASTBuilder.php
  src/Schema/Directives/Args/OrderByDirective.php
  tests/Unit/Schema/Directives/Args/OrderByDirectiveTest.php
Labels: enhancement

#670 Use ExtensionsResponse class for BuildExtensionsResponse
  docs/master/api-reference/events.md
  src/Events/BuildExtensionsResponse.php
  src/Execution/ExtensionsResponse.php
  src/GraphQL.php
  src/Subscriptions/SubscriptionRegistry.php
  src/Tracing/Tracing.php
Labels: bug

#674 Fix tracing precision
  src/Tracing/Tracing.php
  src/Tracing/TracingDirective.php
Labels: bug

#549 Populating nested mutations with other relationships for @update
  docs/master/guides/relationships.md
  src/Execution/MutationExecutor.php
  tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php
  tests/Integration/Execution/MutationExecutor/BelongsToTest.php
  tests/Integration/Execution/MutationExecutor/HasManyTest.php
  tests/Integration/Execution/MutationExecutor/HasOneTest.php
  tests/Integration/Execution/MutationExecutor/MorphManyTest.php
  tests/Integration/Execution/MutationExecutor/MorphOneTest.php
  tests/Integration/Execution/MutationExecutor/MorphToTest.php
  tests/Integration/Schema/Directives/Fields/CreateDirectiveTest.php
  tests/Integration/Schema/Directives/Fields/CreateDirectiveTests/RelationshipTests/BelongsToManyTest.php
  tests/Integration/Schema/Directives/Fields/CreateDirectiveTests/RelationshipTests/BelongsToTest.php
  tests/Integration/Schema/Directives/Fields/CreateDirectiveTests/RelationshipTests/HasManyTest.php
  tests/Integration/Schema/Directives/Fields/CreateDirectiveTests/RelationshipTests/HasOneTest.php
  tests/Integration/Schema/Directives/Fields/CreateDirectiveTests/RelationshipTests/MorphManyTest.php
  tests/Integration/Schema/Directives/Fields/CreateDirectiveTests/RelationshipTests/MorphOneTest.php
  tests/Integration/Schema/Directives/Fields/UpdateDirectiveTest.php
  tests/database/factories/HourFactory.php
  tests/database/migrations/2018_02_28_000003_create_testbench_tasks_table.php
  tests/database/migrations/2018_02_28_000004_create_testbench_posts_table.php
Labels: enhancement

#684 Enable passing in model instance to @can directive
  docs/master/api-reference/directives.md
  src/Schema/Directives/Fields/CanDirective.php
  tests/Unit/Schema/Directives/Fields/CanDirectiveDbTest.php
  tests/Utils/Policies/AuthServiceProvider.php
  tests/Utils/Policies/PostPolicy.php
  tests/Utils/Policies/UserPolicy.php
Labels: enhancement

#686 Properly namespace the model class in the PaginateDirective
  src/Schema/Directives/Fields/PaginateDirective.php
Labels: bug

#689 Convert schema-defined enum default values to internal values
  src/Schema/Directives/Fields/FindDirective.php
  src/Schema/Factories/ArgumentFactory.php
  tests/Unit/Schema/SchemaBuilderTest.php
Labels: bug

#690 Enhance the basics of resolving fields
  docs/master/api-reference/resolvers.md
  docs/master/getting-started/installation.md
  docs/master/guides/plugin-development.md
  docs/master/the-basics/fields.md
  docs/master/the-basics/types.md
  src/Defer/DeferrableDirective.php
  src/LighthouseServiceProvider.php
  src/Schema/Directives/Fields/AllDirective.php
  src/Schema/Directives/Fields/AuthDirective.php
  src/Schema/Directives/Fields/CanDirective.php
  src/Schema/Directives/Fields/EventDirective.php
  src/Schema/Directives/Fields/FirstDirective.php
  src/Schema/Directives/Fields/InjectDirective.php
  src/Schema/Directives/Fields/MethodDirective.php
  src/Schema/Factories/FieldFactory.php
  src/Schema/ResolverProvider.php
  src/Schema/Values/FieldValue.php
  src/Subscriptions/SubscriptionResolverProvider.php
  src/Subscriptions/SubscriptionServiceProvider.php
  src/Support/Contracts/ProvidesResolver.php
  src/Support/Contracts/ProvidesSubscriptionResolver.php
  tests/Integration/CustomDefaultResolverTest.php
  tests/Unit/Schema/ResolverProviderTest.php
Labels: docs, enhancement
