Repository nuwave/lighthouse, pull requests merged in 2020-06, with the labels that each got.

#1390 Add @withCount directive and eager load in @count directive
  CHANGELOG.md
  docs/master/api-reference/directives.md
  src/Execution/DataLoader/RelationBatchLoader.php
  src/Execution/DataLoader/RelationCountBatchLoader.php
  src/Schema/Directives/CountDirective.php
  src/Schema/Directives/WithCountDirective.php
  src/Schema/Directives/WithDirective.php
  src/Schema/Directives/WithRelationDirective.php
  tests/Integration/Execution/DataLoader/RelationCountBatchLoaderTest.php
  tests/Integration/Schema/Directives/CountDirectiveDBTest.php
  tests/Integration/Schema/Directives/WithCountDirectiveTest.php
  tests/Integration/Schema/Directives/WithDirectiveTest.php
  tests/Unit/Schema/Directives/CountDirectiveTest.php
  tests/Utils/Models/Task.php
  tests/Utils/Models/User.php
  tests/database/factories/TaskFactory.php
  tests/database/migrations/2018_02_28_000003_create_testbench_tasks_table.php
Labels: enhancement

#1434 Simplify field generator
  CHANGELOG.md
  docs/master/api-reference/commands.md
  src/Console/FieldGeneratorCommand.php
  src/Console/MutationCommand.php
  src/Console/QueryCommand.php
  src/Console/stubs/field.stub
  src/Console/stubs/field_full.stub
  src/Console/stubs/field_simple.stub
Labels: enhancement

#1139 Document the lifecycle of an incoming GraphQL request
  docs/master/concepts/request-lifecycle.md
Labels: docs

#1447 Fix batched paginated relation queries
  CHANGELOG.md
  src/Execution/DataLoader/ModelRelationFetcher.php
  tests/Integration/Execution/DataLoader/ModelRelationFetcherTest.php
  tests/Utils/Models/Post.php
  tests/Utils/Models/User.php
  tests/database/migrations/2018_02_28_000004_create_testbench_posts_table.php
Labels: bug

#1446 Add cache store option to config
  CHANGELOG.md
  src/Schema/AST/ASTBuilder.php
  src/lighthouse.php
Labels: enhancement

#1451 Add artisan command `lighthouse:cache` to compile GraphQL AST
  CHANGELOG.md
  docs/master/api-reference/commands.md
  src/Console/CacheCommand.php
  src/LighthouseServiceProvider.php
  tests/Unit/Console/CacheCommandTest.php
Labels: enhancement

#1454 Add middleware to log incoming GraphQL queries
  CHANGELOG.md
  src/Support/Http/Middleware/AcceptJson.php
  src/Support/Http/Middleware/AttemptAuthentication.php
  src/Support/Http/Middleware/LogGraphQLQueries.php
  src/lighthouse.php
  tests/TestsSerialization.php
  tests/Unit/Support/Http/Middleware/AcceptJsonTest.php
  tests/Unit/Support/Http/Middleware/LogGraphQLQueriesTest.php
Labels: enhancement
