Repository nuwave/lighthouse, pull requests merged in 2020-12, with the labels that each got.

#1628 Add custom attributes to validation
  CHANGELOG.md
  docs/master/api-reference/directives.md
  docs/master/security/validation.md
  src/Support/Contracts/ArgumentSetValidation.php
  src/Support/Contracts/ArgumentValidation.php
  src/Support/Contracts/ProvidesRules.php
  src/Validation/BaseRulesDirective.php
  src/Validation/RulesDirective.php
  src/Validation/RulesForArrayDirective.php
  src/Validation/RulesGatherer.php
  src/Validation/ValidateDirective.php
  src/Validation/Validator.php
  src/Validation/ValidatorDirective.php
  tests/Integration/Validation/RulesDirectiveTest.php
  tests/Integration/Validation/ValidatorDirectiveTest.php
  tests/Utils/Validators/EmailCustomAttributeValidator.php
Labels: enhancement

#1635 Merge type interfaces when extending type
  CHANGELOG.md
  src/Schema/AST/ASTBuilder.php
  tests/Unit/Schema/AST/ASTBuilderTest.php
Labels: bug

#1640 Add Sanctum cookie endpoint to default CORS paths
  docs/master/getting-started/configuration.md
Labels: docs

#1641 Use the `@trim` directive on fields to sanitize all input strings
  CHANGELOG.md
  docs/master/api-reference/directives.md
  src/Schema/Directives/TrimDirective.php
  src/lighthouse.php
  tests/Integration/Schema/Directives/TrimDirectiveTest.php
Labels: enhancement

#1647 Use Illuminate\Support\Carbon instead of Carbon\Carbon
  CHANGELOG.md
  composer.json
  docs/master/api-reference/events.md
  docs/master/api-reference/scalars.md
  src/Events/StartExecution.php
  src/Events/StartRequest.php
  src/Schema/Directives/CacheDirective.php
  src/Schema/Types/Scalars/Date.php
  src/Schema/Types/Scalars/DateScalar.php
  src/Schema/Types/Scalars/DateTime.php
  src/Schema/Types/Scalars/DateTimeTz.php
  src/Schema/Types/Scalars/DateTimeUtc.php
  src/Subscriptions/StorageManager.php
  src/Tracing/Tracing.php
  tests/Unit/Schema/Types/Scalars/DateScalarTest.php
  tests/Unit/Schema/Types/Scalars/DateTimeUtcTest.php
  tests/Utils/Models/Activity.php
  tests/Utils/Models/Category.php
  tests/Utils/Models/Color.php
  tests/Utils/Models/Comment.php
  tests/Utils/Models/Company.php
  tests/Utils/Models/Contractor.php
  tests/Utils/Models/Employee.php
  tests/Utils/Models/Image.php
  tests/Utils/Models/Post.php
  tests/Utils/Models/Product.php
  tests/Utils/Models/Tag.php
  tests/Utils/Models/Task.php
  tests/Utils/Models/Team.php
  tests/Utils/Models/User.php
Labels: enhancement

#1370 Add Laravel Echo compatible subscription broadcaster
  .github/workflows/continuous-integration.yml
  CHANGELOG.md
  composer.json
  docker-compose.yml
  docs/.github/README.md
  docs/master/subscriptions/client-implementations.md
  docs/master/subscriptions/getting-started.md
  php.dockerfile
  src/Subscriptions/Authorizer.php
  src/Subscriptions/BroadcastManager.php
  src/Subscriptions/Broadcasters/EchoBroadcaster.php
  src/Subscriptions/Broadcasters/LogBroadcaster.php
  src/Subscriptions/Broadcasters/PusherBroadcaster.php
  src/Subscriptions/Contracts/AuthorizesSubscriptions.php
  src/Subscriptions/Contracts/Broadcaster.php
  src/Subscriptions/Events/EchoSubscriptionEvent.php
  src/Subscriptions/Storage/CacheStorageManager.php
  src/Subscriptions/Storage/RedisStorageManager.php
  src/Subscriptions/SubscriptionBroadcaster.php
  src/Subscriptions/SubscriptionRouter.php
  src/Subscriptions/SubscriptionServiceProvider.php
  src/lighthouse.php
  tests/Console/IdeHelperCommandTest.php
  tests/DBTestCase.php
  tests/Integration/RouteRegistrationTest.php
  tests/Integration/SchemaCachingTest.php
  tests/Integration/Subscriptions/EchoBroadcaster/AuthorizeRequestsTest.php
  tests/Integration/Subscriptions/EchoBroadcaster/EchoTestCase.php
  tests/Integration/Subscriptions/Storage/RedisStorageManagerTest.php
  tests/Integration/Subscriptions/SubscriptionTest.php
  tests/Integration/Validation/RulesDirectiveTest.php
  tests/Integration/Validation/ValidationTest.php
  tests/TestCase.php
  tests/TestsSerialization.php
  tests/Unit/Subscriptions/BroadcastManagerTest.php
  tests/Unit/Subscriptions/Broadcasters/EchoBroadcasterTest.php
  tests/Unit/Subscriptions/Storage/CacheStorageManagerTest.php
  tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
  tests/Unit/Subscriptions/SubscriptionTestCase.php
  tests/Unit/Testing/MakesGraphQLRequestsTest.php
  tests/Utils/Subscriptions/DummySubscriber.php
  tests/Utils/Subscriptions/TaskCreated.php
Labels: enhancement

#1649 Allow auxiliary types in directive definitions
  .github/workflows/continuous-integration.yml
  CHANGELOG.md
  docs/master/api-reference/directives.md
  docs/master/digging-deeper/relay.md
  src/Console/IdeHelperCommand.php
  src/GlobalId/GlobalIdDirective.php
  src/Pagination/PaginateDirective.php
  src/Pagination/PaginationType.php
  src/Schema/AST/ASTHelper.php
  src/Schema/DirectiveLocator.php
  src/Schema/Directives/BelongsToManyDirective.php
  src/Schema/Directives/BroadcastDirective.php
  src/Schema/Directives/HasManyDirective.php
  src/Schema/Directives/MorphManyDirective.php
  src/Schema/Directives/ScopeDirective.php
  src/Support/Contracts/Directive.php
  tests/Integration/Events/FieldDirective.php
  tests/Integration/Pagination/PaginateDirectiveDBTest.php
  tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
  tests/Integration/Schema/Directives/CacheDirectiveTest.php
  tests/Integration/Schema/Directives/HasManyDirectiveTest.php
  tests/Integration/Schema/Directives/MorphManyDirectiveTest.php
  tests/Integration/Schema/Directives/SearchDirectiveTest.php
  tests/Integration/Schema/Types/UnionTest.php
  tests/Unit/Pagination/PaginateDirectiveTest.php
  tests/Unit/Schema/AST/ASTHelperTest.php
  tests/Unit/Schema/Factories/DirectiveFactoryTest.php
Labels: enhancement
