Repository nuwave/lighthouse, pull requests merged in 2020-07, with the labels that each got.

#1487 Allow custom query validation rules selection
  CHANGELOG.md
  docs/master/security/validation.md
  src/Execution/ValidationRulesProvider.php
  src/GraphQL.php
  src/LighthouseServiceProvider.php
  src/Support/Contracts/ProvidesValidationRules.php
Labels: enhancement

#1458 docs: clarify usage with laravel sanctum, login / logout mutations
  docs/master/security/authentication.md
Labels: docs

#1420 Throw partial errors when failing to delete, forceDelete or restore a model
  CHANGELOG.md
  UPGRADE.md
  docs/master/digging-deeper/error-handling.md
  docs/master/security/authentication.md
  docs/master/security/validation.md
  src/Execution/ErrorBuffer.php
  src/Execution/ErrorPool.php
  src/GraphQL.php
  src/LighthouseServiceProvider.php
  src/Schema/Directives/DeleteDirective.php
  src/Schema/Directives/ModifyModelExistenceDirective.php
  src/SoftDeletes/ForceDeleteDirective.php
  src/SoftDeletes/RestoreDirective.php
  tests/Integration/Schema/Directives/DeleteDirectiveTest.php
Labels: enhancement

#1320 Add DateTimeUtc scalar
  CHANGELOG.md
  assets/default-schema.graphql
  docs/master/api-reference/scalars.md
  src/Schema/Types/Scalars/DateTimeUtc.php
  tests/Unit/Schema/Types/Scalars/DateScalarTest.php
  tests/Unit/Schema/Types/Scalars/DateTest.php
  tests/Unit/Schema/Types/Scalars/DateTimeTest.php
  tests/Unit/Schema/Types/Scalars/DateTimeTzTest.php
  tests/Unit/Schema/Types/Scalars/DateTimeUtcTest.php
Labels: enhancement

#1439 Fix missing route prefix in test url
  src/Testing/MakesGraphQLRequests.php
  src/Testing/MakesGraphQLRequestsLumen.php
  tests/Integration/GraphQLTest.php
  tests/TestCase.php
  tests/Unit/Testing/MakesGraphQLRequestsTest.php
Labels: bug

#1192 Remove support for PHP 7.1, Laravel 5.5 and PHPUnit 6
  .github/workflows/continuous-integration.yml
  CHANGELOG.md
  UPGRADE.md
  _ide_helper.php
  composer.json
  docs/master/custom-directives/argument-directives.md
  src/Execution/Arguments/ArgumentSet.php
  src/Execution/Arguments/ArgumentTypeNodeConverter.php
  src/OrderBy/OrderByDirective.php
  src/Pagination/PaginationArgs.php
  src/Schema/Directives/BuilderDirective.php
  src/Schema/Directives/EqDirective.php
  src/Schema/Directives/InDirective.php
  src/Schema/Directives/NeqDirective.php
  src/Schema/Directives/NotInDirective.php
  src/Schema/Directives/ScopeDirective.php
  src/Schema/Directives/SearchDirective.php
  src/Schema/Directives/WhereBetweenDirective.php
  src/Schema/Directives/WhereDirective.php
  src/Schema/Directives/WhereJsonContainsDirective.php
  src/Schema/Directives/WhereNotBetweenDirective.php
  src/Schema/Values/CacheValue.php
  src/SoftDeletes/TrashedDirective.php
  src/Support/Http/routes.php
  src/Testing/MakesGraphQLRequests.php
  src/Testing/MocksResolvers.php
  src/Testing/TestResponseMixin.php
  src/WhereConditions/WhereConditionsBaseDirective.php
  src/WhereConditions/WhereConditionsDirective.php
  src/WhereConditions/WhereHasConditionsDirective.php
  tests/DBTestCase.php
  tests/Integration/Defer/DeferTest.php
  tests/Integration/GraphQLTest.php
  tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
  tests/Integration/Schema/Directives/BuilderDirectiveTest.php
  tests/Integration/Schema/Directives/CacheDirectiveTest.php
  tests/Integration/Schema/Directives/HasManyDirectiveTest.php
  tests/Integration/Schema/Directives/MorphManyDirectiveTest.php
  tests/Integration/Schema/Directives/WhereJsonContainsDirectiveDBTest.php
  tests/Integration/Schema/Types/InterfaceTest.php
  tests/Integration/Subscriptions/SubscriptionTest.php
  tests/Integration/Tracing/TracingExtensionTest.php
  tests/Integration/ValidationTest.php
  tests/Unit/Schema/Directives/BcryptDirectiveTest.php
  tests/Unit/Schema/Directives/DeprecatedDirectiveTest.php
  tests/Unit/Schema/Directives/HashDirectiveTest.php
  tests/Unit/Schema/Directives/PaginateDirectiveTest.php
  tests/Unit/Schema/Directives/RulesDirectiveTest.php
  tests/Unit/Schema/SecurityTest.php
Labels: 5.x

#1298 Replace deprecated `assertContains` by `assertStringContainsString`
  tests/Console/IdeHelperCommandTest.php
  tests/Console/PrintSchemaCommandTest.php
  tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
Labels: 5.x

#1337 Fully qualified names for generated inputs
  CHANGELOG.md
  UPGRADE.md
  docs/master/api-reference/directives.md
  docs/master/eloquent/complex-where-conditions.md
  src/OrderBy/OrderByDirective.php
  src/OrderBy/OrderByServiceProvider.php
  src/Schema/AST/ASTHelper.php
  src/Support/Traits/GeneratesColumnsEnum.php
  src/WhereConditions/WhereConditionsBaseDirective.php
  src/WhereConditions/WhereConditionsDirective.php
  src/WhereConditions/WhereHasConditionsDirective.php
  src/lighthouse.php
  tests/Integration/OrderBy/OrderByDirectiveDBTest.php
  tests/Integration/OrderBy/OrderByDirectiveTest.php
  tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
Labels: 5.x

#1422 Only invoke default resolver
  CHANGELOG.md
  UPGRADE.md
  src/Schema/ResolverProvider.php
  tests/Unit/Schema/Directives/FieldDirectiveTest.php
  tests/Unit/Schema/Directives/NamespaceDirectiveTest.php
  tests/Unit/Schema/ResolverProviderTest.php
  tests/Utils/InterfacesSecondary/Bar.php
  tests/Utils/Mutations/Foo.php
  tests/Utils/Mutations/Upload.php
  tests/Utils/Queries/Foo.php
  tests/Utils/Queries/FooBar.php
  tests/Utils/Queries/FooInvoke.php
  tests/Utils/Queries/MissingInvoke.php
  tests/Utils/QueriesSecondary/Baz.php
  tests/Utils/QueriesSecondary/Foo.php
Labels: 5.x

#1423 Remove fallback for `lighthouse.cache.ttl` setting
  CHANGELOG.md
  src/Schema/AST/ASTBuilder.php
Labels: 5.x

#834 Add test for multiple where directives
  docker-compose.yml
  src/Execution/Arguments/ArgumentSet.php
  tests/Integration/Execution/ArgBuilderDirectiveTest.php
Labels: 5.x

#1457 Replace PartialParser.php in favor of webonyx/graphql-php
  CHANGELOG.md
  UPGRADE.md
  composer.json
  phpstan.neon
  src/ClientDirectives/ClientDirective.php
  src/ClientDirectives/ClientDirectiveFactory.php
  src/Console/IdeHelperCommand.php
  src/Console/PrintSchemaCommand.php
  src/Defer/Defer.php
  src/Exceptions/DirectiveException.php
  src/Execution/ErrorPool.php
  src/Execution/ExtensionErrorHandler.php
  src/GraphQL.php
  src/OrderBy/OrderByDirective.php
  src/OrderBy/OrderByServiceProvider.php
  src/Pagination/PaginationManipulator.php
  src/Schema/AST/ASTBuilder.php
  src/Schema/AST/ASTHelper.php
  src/Schema/AST/DocumentAST.php
  src/Schema/AST/PartialParser.php
  src/Schema/AST/TypeNodeConverter.php
  src/Schema/Directives/CacheDirective.php
  src/Schema/Directives/CountDirective.php
  src/Schema/Directives/InjectDirective.php
  src/Schema/Directives/MiddlewareDirective.php
  src/Schema/Directives/RelationDirective.php
  src/Schema/Directives/WithRelationDirective.php
  src/Schema/Factories/ArgumentFactory.php
  src/Schema/Factories/DirectiveFactory.php
  src/Schema/TypeRegistry.php
  src/SoftDeletes/SoftDeletesDirective.php
  src/SoftDeletes/SoftDeletesServiceProvider.php
  src/Subscriptions/Subscriber.php
  src/Support/Traits/GeneratesColumnsEnum.php
  src/Tracing/Tracing.php
  src/Validation/ValidatorDirective.php
  src/WhereConditions/WhereConditionsBaseDirective.php
  src/WhereConditions/WhereConditionsServiceProvider.php
  src/lighthouse.php
  tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
  tests/Integration/Execution/DataLoader/RelationCountBatchLoaderTest.php
  tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
  tests/TestCase.php
  tests/Unit/Events/ManipulateASTTest.php
  tests/Unit/Execution/Arguments/ArgumentSetTest.php
  tests/Unit/Schema/AST/ASTBuilderTest.php
  tests/Unit/Schema/AST/ASTHelperTest.php
  tests/Unit/Schema/AST/DocumentASTTest.php
  tests/Unit/Schema/AST/PartialParserTest.php
  tests/Unit/Schema/ClientDirectiveTest.php
  tests/Unit/Schema/Directives/BaseDirectiveTest.php
  tests/Unit/Schema/Directives/ComplexityDirectiveTest.php
  tests/Unit/Schema/Directives/CountDirectiveTest.php
  tests/Unit/Schema/Directives/PaginateDirectiveTest.php
  tests/Unit/Schema/Factories/DirectiveFactoryTest.php
  tests/Unit/Schema/ResolverProviderTest.php
  tests/Unit/Schema/SchemaBuilderTest.php
  tests/Unit/Schema/TypeRegistryTest.php
Labels: 5.x

#1412 Added ability to handle relations in base where conditions
  UPGRADE.md
  src/WhereConditions/Operator.php
  src/WhereConditions/SQLOperator.php
  src/WhereConditions/WhereConditionsBaseDirective.php
  src/WhereConditions/WhereConditionsServiceProvider.php
  src/WhereConditions/WhereHasConditionsDirective.php
  tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
Labels: 5.x, enhancement
