Repository nuwave/lighthouse, pull requests merged in 2021-04, with the labels that each got.

#1791 Fix wrong docs of @paginate with CONNECTION type
  docs/5.0/api-reference/directives.md
  docs/5.1/api-reference/directives.md
  docs/5.2/api-reference/directives.md
  docs/5.3/api-reference/directives.md
  docs/master/api-reference/directives.md
Labels: docs

#1792 Fix `@paginate` docs and include descriptions
  docs/4.10/api-reference/directives.md
  docs/4.11/api-reference/directives.md
  docs/4.12/api-reference/directives.md
  docs/4.13/api-reference/directives.md
  docs/4.14/api-reference/directives.md
  docs/4.15/api-reference/directives.md
  docs/4.16/api-reference/directives.md
  docs/4.17/api-reference/directives.md
  docs/4.18/api-reference/directives.md
  docs/4.9/api-reference/directives.md
  docs/master/api-reference/directives.md
  src/Pagination/PaginationManipulator.php
Labels: docs

#1798 Fix webonyx.github.io/graphql-php documentation links
  docs/5.3/api-reference/directives.md
  docs/5.3/digging-deeper/adding-types-programmatically.md
  docs/5.3/the-basics/types.md
  docs/master/api-reference/directives.md
  docs/master/digging-deeper/adding-types-programmatically.md
  docs/master/the-basics/types.md
Labels: docs

#1803 Move subscription related classes into Subscription namespace
  CHANGELOG.md
  src/SoftDeletes/SoftDeletesServiceProvider.php
  src/Subscriptions/Directives/BroadcastDirective.php
  src/Subscriptions/Directives/SubscriptionDirective.php
  src/Subscriptions/SubscriptionController.php
  src/Subscriptions/SubscriptionResolverProvider.php
  src/Subscriptions/SubscriptionRouter.php
  src/Subscriptions/SubscriptionServiceProvider.php
Labels: enhancement

#1804 Consolidate GlobalId namespace
  CHANGELOG.md
  docs/4.10/api-reference/directives.md
  docs/4.11/api-reference/directives.md
  docs/4.12/api-reference/directives.md
  docs/4.13/api-reference/directives.md
  docs/4.14/api-reference/directives.md
  docs/4.15/api-reference/directives.md
  docs/4.16/api-reference/directives.md
  docs/4.17/api-reference/directives.md
  docs/4.18/api-reference/directives.md
  docs/4.5/api-reference/directives.md
  docs/4.6/api-reference/directives.md
  docs/4.7/api-reference/directives.md
  docs/4.8/api-reference/directives.md
  docs/4.9/api-reference/directives.md
  docs/5.0/api-reference/directives.md
  docs/5.1/api-reference/directives.md
  docs/5.2/api-reference/directives.md
  docs/5.3/api-reference/directives.md
  docs/master/api-reference/directives.md
  src/GlobalId/GlobalIdServiceProvider.php
  src/GlobalId/NodeDirective.php
  src/Schema/Directives/ModifyModelExistenceDirective.php
  src/Schema/Directives/UpsertDirective.php
  src/Support/Contracts/GlobalId.php
  tests/Integration/GlobalId/NodeDirectiveDBTest.php
Labels: enhancement

#1799 Add config option `subscriptions.exclude_empty`
  CHANGELOG.md
  docs/master/subscriptions/getting-started.md
  src/Subscriptions/SubscriptionRegistry.php
  src/lighthouse.php
  tests/Integration/Subscriptions/SubscriptionTest.php
Labels: enhancement

#1739 Prepend rule arguments that refer to other arguments with the full path
  CHANGELOG.md
  docs/master/security/validation.md
  src/Validation/RulesGatherer.php
  tests/Integration/Validation/ValidationTest.php
  tests/Integration/Validation/ValidatorDirectiveTest.php
  tests/Utils/Validators/BarRequiredWithoutFooValidator.php
Labels: bug

#1819 Add method `assertGraphQLErrorMessage()` to `TestResponse` mixin
  CHANGELOG.md
  _ide_helper.php
  src/Testing/TestResponseMixin.php
  tests/Integration/Defer/DeferTest.php
  tests/Integration/ErrorTest.php
  tests/Integration/Schema/Directives/CanDirectiveDBTest.php
  tests/Integration/Schema/Directives/DeleteDirectiveTest.php
  tests/Integration/Schema/Directives/ThrottleDirectiveTest.php
  tests/Integration/Schema/Directives/UpdateDirectiveTest.php
  tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
  tests/Unit/Schema/Directives/CanDirectiveTest.php
  tests/Unit/Schema/Directives/GuardDirectiveTest.php
Labels: enhancement

#1728 Support for Apollo Federation
  CHANGELOG.md
  docs/master/api-reference/directives.md
  docs/master/digging-deeper/client-directives.md
  docs/master/eloquent/complex-where-conditions.md
  docs/master/federation/entities.md
  docs/master/federation/getting-started.md
  docs/master/performance/deferred.md
  docs/master/sidebar.js
  src/Exceptions/FederationException.php
  src/Execution/Arguments/NestedOneToMany.php
  src/Execution/DataLoader/RelationCountLoader.php
  src/Execution/DataLoader/SimpleRelationLoader.php
  src/Federation/ASTManipulator.php
  src/Federation/Directives/ExtendsDirective.php
  src/Federation/Directives/ExternalDirective.php
  src/Federation/Directives/KeyDirective.php
  src/Federation/Directives/ProvidesDirective.php
  src/Federation/Directives/RequiresDirective.php
  src/Federation/EntityResolverProvider.php
  src/Federation/FederationPrinter.php
  src/Federation/FederationServiceProvider.php
  src/Federation/Resolvers/Entities.php
  src/Federation/Resolvers/Service.php
  src/Federation/SchemaPrinter.php
  src/Federation/SchemaValidator.php
  src/Federation/Types/Any.php
  src/Federation/Types/FieldSet.php
  src/Schema/AST/ASTBuilder.php
  src/Schema/SchemaBuilder.php
  src/Subscriptions/Authorizer.php
  src/lighthouse.php
  tests/Integration/Federation/FederationEntitiesTest.php
  tests/Integration/Federation/FederationSchemaTest.php
  tests/Integration/Subscriptions/EchoBroadcaster/AuthorizeRequestsTest.php
  tests/Integration/Subscriptions/Storage/RedisStorageManagerTest.php
  tests/TestCase.php
  tests/Unit/Federation/ExternalDirectiveTest.php
  tests/Unit/Federation/SchemaBuilderTest.php
  tests/Unit/Federation/SchemaValidatorTest.php
  tests/Unit/Subscriptions/Iterators/AuthenticatingSyncIteratorTest.php
  tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
  tests/Utils/Entities/Foo.php
Labels: enhancement

#1824 Fix overly eager validation of repeatable directive usage
  CHANGELOG.md
  composer.json
  src/Schema/Factories/DirectiveFactory.php
  tests/Unit/Schema/DirectiveLocatorTest.php
  tests/Unit/Schema/Factories/DirectiveFactoryTest.php
Labels: bug

#1827 Update behavior of TestReponse::assertGraphQLErrorMessage to work whe…
  CHANGELOG.md
  src/Testing/TestResponseMixin.php
  tests/Integration/ErrorTest.php
Labels: enhancement

#1831 Fix usage of closures in validation
  CHANGELOG.md
  src/Validation/RulesGatherer.php
  tests/Integration/Validation/ValidationTest.php
  tests/Utils/Validators/FooClosureValidator.php
Labels: bug
