Repository nuwave/lighthouse, pull requests merged in 2021-05, with the labels that each got.

#1816 Add `SIMPLE` pagination type
  CHANGELOG.md
  docs/master/api-reference/directives.md
  src/Pagination/PaginateDirective.php
  src/Pagination/PaginationArgs.php
  src/Pagination/PaginationManipulator.php
  src/Pagination/PaginationServiceProvider.php
  src/Pagination/PaginationType.php
  src/Pagination/SimplePaginatorField.php
  src/Schema/Directives/BelongsToManyDirective.php
  src/Schema/Directives/HasManyDirective.php
  src/Schema/Directives/MorphManyDirective.php
  tests/Integration/Pagination/PaginateDirectiveDBTest.php
  tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
  tests/Integration/Schema/Directives/HasManyDirectiveTest.php
  tests/Integration/Schema/Directives/MorphManyDirectiveTest.php
  tests/Unit/Pagination/PaginateDirectiveTest.php
Labels: enhancement

#1837 Avoid setting multiple `@model` directives on generated paginator types
  CHANGELOG.md
  src/LighthouseServiceProvider.php
  src/Pagination/PaginateDirective.php
  src/Pagination/PaginationManipulator.php
  src/Schema/Directives/CacheDirective.php
  src/Schema/Directives/CacheKeyDirective.php
  src/Schema/Directives/ModelDirective.php
  tests/TestCase.php
  tests/TestsSerialization.php
  tests/Unit/Pagination/PaginateDirectiveTest.php
  tests/Unit/Schema/DirectiveLocatorTest.php
  tests/Unit/Schema/Directives/BaseDirectiveTest.php
  tests/Unit/Schema/Execution/ContextFactoryTest.php
  tests/Unit/Subscriptions/BroadcastManagerTest.php
  tests/Unit/Subscriptions/SubscriptionTest.php
Labels: bug

#1847 Improve validation docs
  docs/4/subscriptions/client-implementations.md
  docs/5/security/validation.md
  docs/5/subscriptions/client-implementations.md
  docs/master/security/validation.md
  docs/master/subscriptions/client-implementations.md
  src/Validation/ValidationServiceProvider.php
Labels: docs

#1850 Allow `@builder` in combination with `@search`
  CHANGELOG.md
  src/Schema/Directives/BuilderDirective.php
  tests/Integration/Scout/SearchDirectiveTest.php
Labels: bug

#1851 Make use of the new graphql-php lazy field definition feature
  CHANGELOG.md
  composer.json
  src/Schema/SchemaBuilder.php
  src/Schema/TypeRegistry.php
  src/Subscriptions/SubscriptionRegistry.php
  src/Support/Contracts/ProvidesSubscriptionResolver.php
  tests/Unit/Schema/Directives/RenameDirectiveTest.php
  tests/Unit/Subscriptions/SubscriptionTest.php
Labels: enhancement, performance

#1856 Add lifecycle events `StartOperationOrOperations` and `EndOperationOrOperations`
  CHANGELOG.md
  docs/5/api-reference/events.md
  docs/master/api-reference/events.md
  src/Events/EndExecution.php
  src/Events/EndOperationOrOperations.php
  src/Events/StartExecution.php
  src/Events/StartOperationOrOperations.php
  src/GraphQL.php
  tests/Integration/LifecycleEventsTest.php
Labels: enhancement

#1857 Add `ValidationException::withMessage()`
  src/Exceptions/ValidationException.php
  tests/Unit/Exceptions/ValidationExceptionTest.php
Labels: enhancement

#1862 Handle `null` when encoding or decoding with `@globalId`
  CHANGELOG.md
  src/GlobalId/GlobalIdDirective.php
  tests/Unit/GlobalId/GlobalIdDirectiveTest.php
Labels: bug

#1864 Allow JSON notation `->` in column references for complex where conditions
  CHANGELOG.md
  src/WhereConditions/WhereConditionsBaseDirective.php
  tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
  tests/Utils/Models/Location.php
  tests/database/factories/LocationFactory.php
  tests/database/migrations/2021_04_14_000000_create_testbench_locations_table.php
Labels: bug
