Repository nuwave/lighthouse, pull requests merged in 2021-01, with the labels that each got.

#1656 doc: mention `mll-lab/graphql-php-scalars` update in the upgrade guide
  UPGRADE.md
Labels: docs

#1659 Force load type when GlobalId\Node is used
  CHANGELOG.md
  src/GlobalId/NodeRegistry.php
  tests/Integration/Schema/NodeInterfaceTest.php
Labels: bug

#1662 Allow spec-compliant definition of message on `@rules` and `@rulesForArray`
  CHANGELOG.md
  UPGRADE.md
  docs/master/api-reference/directives.md
  docs/master/security/validation.md
  src/Validation/BaseRulesDirective.php
  src/Validation/RulesDirective.php
  src/Validation/RulesForArrayDirective.php
  tests/Integration/Validation/RulesDirectiveTest.php
Labels: enhancement

#1672 Ensure Carbon\Carbon is cast to Illuminate\Support\Carbon in date scalars
  CHANGELOG.md
  src/Schema/Types/Scalars/DateScalar.php
  tests/Unit/Schema/Types/Scalars/DateScalarTest.php
Labels: bug

#1528 Rework batch loading
  CHANGELOG.md
  src/Execution/DataLoader/BatchLoader.php
  src/Execution/DataLoader/BatchLoaderRegistry.php
  src/Execution/DataLoader/ModelRelationFetcher.php
  src/Execution/DataLoader/PaginatedRelationLoader.php
  src/Execution/DataLoader/RelationBatchLoader.php
  src/Execution/DataLoader/RelationCountBatchLoader.php
  src/Execution/DataLoader/RelationCountLoader.php
  src/Execution/DataLoader/RelationFetcher.php
  src/Execution/DataLoader/RelationLoader.php
  src/Execution/DataLoader/SimpleRelationLoader.php
  src/GraphQL.php
  src/Schema/Directives/CountDirective.php
  src/Schema/Directives/RelationDirective.php
  src/Schema/Directives/WithCountDirective.php
  src/Schema/Directives/WithDirective.php
  src/Schema/Directives/WithRelationDirective.php
  tests/Integration/Execution/DataLoader/PaginatedRelationLoaderTest.php
  tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
  tests/Integration/Execution/DataLoader/RelationCountBatchLoaderTest.php
  tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
  tests/Integration/Schema/Directives/CountDirectiveDBTest.php
  tests/Integration/Schema/Directives/WithCountDirectiveTest.php
  tests/Integration/Schema/Directives/WithDirectiveTest.php
  tests/Integration/Schema/Types/LaravelEnumTypeDBTest.php
  tests/Unit/Schema/Directives/CountDirectiveTest.php
  tests/Utils/Models/User.php
Labels: enhancement, performance

#1676 Fix typo in authentication docs
  docs/5.0/security/authentication.md
Labels: docs

#1673 Clean up definition and implementation of `@node`
  composer.json
  docs/4.0/api-reference/directives.md
  docs/4.1/api-reference/directives.md
  docs/4.10/api-reference/directives.md
  docs/4.11/api-reference/directives.md
  docs/4.12/api-reference/directives.md
  docs/4.13/api-reference/directives.md
  docs/4.14/api-reference/directives.md
  docs/4.15/api-reference/directives.md
  docs/4.16/api-reference/directives.md
  docs/4.17/api-reference/directives.md
  docs/4.18/api-reference/directives.md
  docs/4.2/api-reference/directives.md
  docs/4.3/api-reference/directives.md
  docs/4.4/api-reference/directives.md
  docs/4.5/api-reference/directives.md
  docs/4.6/api-reference/directives.md
  docs/4.7/api-reference/directives.md
  docs/4.8/api-reference/directives.md
  docs/4.9/api-reference/directives.md
  docs/5.0/api-reference/directives.md
  docs/master/api-reference/directives.md
  src/Schema/AST/ASTHelper.php
  src/Schema/Directives/NodeDirective.php
  tests/Integration/ErrorHandlersTest.php
  tests/Integration/Schema/NodeDirectiveDBTest.php
Labels: enhancement

#1675 Simplify merging AST NodeList's to pushing added nodes
  src/GlobalId/GlobalIdServiceProvider.php
  src/Pagination/PaginationManipulator.php
  src/Schema/AST/ASTHelper.php
  src/Schema/Directives/NamespaceDirective.php
  src/SoftDeletes/SoftDeletesDirective.php
  src/Support/Contracts/TypeManipulator.php
  tests/Integration/SoftDeletes/SoftDeletesAndTrashedDirectiveTest.php
Labels: enhancement

#1683 Fix subscriptions renaming variables
  CHANGELOG.md
  src/Subscriptions/Subscriber.php
  src/Subscriptions/SubscriptionBroadcaster.php
Labels: bug

#1685 Fix TTL for subscriptions
  CHANGELOG.md
  src/Subscriptions/Storage/RedisStorageManager.php
  tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
Labels: bug

#1645 Add `@like` directive
  CHANGELOG.md
  src/Schema/Directives/LikeDirective.php
  tests/Integration/Schema/Directives/LikeDirectiveTest.php
Labels: enhancement

#1691 Handle builders in a typesafe way
  CHANGELOG.md
  docs/.github/README.md
  docs/master/api-reference/directives.md
  phpstan.neon
  src/Execution/Arguments/ArgumentSet.php
  src/OrderBy/OrderByDirective.php
  src/Pagination/PaginationArgs.php
  src/Schema/Directives/BuilderDirective.php
  src/Schema/Directives/EqDirective.php
  src/Schema/Directives/InDirective.php
  src/Schema/Directives/LikeDirective.php
  src/Schema/Directives/NeqDirective.php
  src/Schema/Directives/NotInDirective.php
  src/Schema/Directives/RelationDirective.php
  src/Schema/Directives/ScopeDirective.php
  src/Schema/Directives/SearchDirective.php
  src/Schema/Directives/WhereAuthDirective.php
  src/Schema/Directives/WhereBetweenDirective.php
  src/Schema/Directives/WhereDirective.php
  src/Schema/Directives/WhereJsonContainsDirective.php
  src/Schema/Directives/WhereNotBetweenDirective.php
  src/Schema/Directives/WithRelationDirective.php
  src/Scout/ScoutBuilderDirective.php
  src/Scout/ScoutEnhancer.php
  src/Scout/ScoutException.php
  src/SoftDeletes/TrashedDirective.php
  src/Support/Contracts/ArgBuilderDirective.php
  src/Support/Contracts/FieldBuilderDirective.php
  src/WhereConditions/WhereConditionsDirective.php
  src/WhereConditions/WhereHasConditionsDirective.php
  tests/Integration/Schema/Directives/SearchDirectiveTest.php
  tests/Integration/SoftDeletes/SoftDeletesAndTrashedDirectiveTest.php
Labels: enhancement

#1681 Allow `@eq` directive on fields
  CHANGELOG.md
  docs/master/api-reference/directives.md
  src/Schema/Directives/EqDirective.php
  tests/Integration/Execution/ArgBuilderDirectiveTest.php
  tests/Integration/Schema/Directives/EqDirectiveTest.php
Labels: enhancement

#1697 Add benchmark to measure performance of queries with many results
  benchmarks/HugeResponseBench.php
  benchmarks/QueryBench.php
  src/Testing/MakesGraphQLRequests.php
  src/Testing/MocksResolvers.php
  tests/DBTestCase.php
  tests/Integration/Defer/DeferTest.php
  tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
  tests/Integration/IntrospectionTest.php
  tests/Integration/Schema/Directives/BelongsToDirectiveTest.php
  tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
  tests/Integration/Schema/Directives/HasManyDirectiveTest.php
  tests/Integration/Schema/Directives/MorphManyDirectiveTest.php
  tests/Integration/Schema/Directives/MorphOneDirectiveTest.php
  tests/Integration/Schema/Directives/MorphToDirectiveTest.php
  tests/Integration/Schema/Directives/MorphToManyDirectiveTest.php
  tests/Integration/Schema/NodeDirectiveDBTest.php
  tests/Integration/Schema/Types/LaravelEnumTypeDBTest.php
  tests/Integration/Scout/SearchDirectiveTest.php
  tests/Integration/Subscriptions/Broadcast/BroadcastDBTest.php
  tests/Integration/Subscriptions/SubscriptionTest.php
  tests/TestCase.php
  tests/Unit/GlobalId/GlobalIdDirectiveTest.php
  tests/Unit/GlobalId/GlobalIdTest.php
  tests/Unit/Schema/AST/ASTBuilderTest.php
  tests/Unit/Schema/AST/SchemaStitcherTest.php
  tests/Unit/Schema/ResolverProviderTest.php
  tests/Unit/Schema/Source/SchemaSourceProviderTest.php
  tests/Unit/Schema/TypeRegistryTest.php
  tests/Unit/Schema/Types/LaravelEnumTypeTest.php
  tests/Unit/Schema/Types/Scalars/DateTimeUtcTest.php
  tests/Unit/Subscriptions/BroadcastManagerTest.php
  tests/Unit/Subscriptions/Storage/CacheStorageManagerTest.php
  tests/Unit/Subscriptions/SubscriptionTest.php
Labels: performance
