Repository nuwave/lighthouse, pull requests merged in 2021-08, with the labels that each got.

#1911 Fix compatibility with Laravel Octane
  CHANGELOG.md
  docs/5/api-reference/directives.md
  docs/master/api-reference/directives.md
  src/Validation/ValidateDirective.php
Labels: bug

#1919 Add `query` and `scopes` arguments to the `@can` directive
  CHANGELOG.md
  docs/master/api-reference/directives.md
  docs/master/security/authorization.md
  src/Schema/Directives/CanDirective.php
  tests/Integration/Schema/Directives/CanDirectiveDBTest.php
  tests/Integration/SoftDeletes/ForceDeleteDirectiveTest.php
  tests/Integration/SoftDeletes/RestoreDirectiveTest.php
  tests/Unit/Schema/Directives/CanDirectiveTest.php
Labels: enhancement

#1920 Add trait to clear the schema cache once before any tests are run
  CHANGELOG.md
  docs/master/testing/phpunit.md
  src/Testing/ClearsSchemaCache.php
Labels: enhancement

#1925 Support schema without `Query` type when using federation
  CHANGELOG.md
  src/Console/MutationCommand.php
  src/Console/QueryCommand.php
  src/Console/SubscriptionCommand.php
  src/Federation/ASTManipulator.php
  src/Federation/FederationPrinter.php
  tests/Integration/Federation/FederationSchemaTest.php
  tests/Unit/Federation/SchemaBuilderTest.php
Labels: discussion

#1927 Fix phpbench
  .github/workflows/validate.yml
  CONTRIBUTING.md
  Makefile
  benchmarks/HugeResponseBench.php
  benchmarks/QueryBench.php
  composer.json
  phpbench.json
Labels: bug
