Repository nuwave/lighthouse, pull requests merged in 2022-04, with the labels that each got.

#2104 Revert breaking schema change in generate pagination types
  CHANGELOG.md
  UPGRADE.md
  src/Pagination/PaginationManipulator.php
  tests/Integration/Pagination/PaginateDirectiveDBTest.php
  tests/Unit/Pagination/PaginateDirectiveTest.php
Labels: bug

#2119 Fix hasMany connect disconnect with non-default primary key
  src/Execution/Arguments/NestedOneToMany.php
  tests/Integration/Execution/MutationExecutor/HasManyTest.php
  tests/Utils/Models/CustomPrimaryKey.php
  tests/Utils/Models/User.php
  tests/database/factories/CustomPrimaryKeyFactory.php
  tests/database/migrations/2022_04_14_000000_create_testbench_custom_primary_keys_table.php
Labels: bug

#2120 Fix assert for builder argument on @all & @paginate directives
  CHANGELOG.md
  src/Execution/Arguments/ArgumentSet.php
  src/Pagination/PaginateDirective.php
  src/Schema/Directives/AllDirective.php
  src/Scout/ScoutEnhancer.php
  tests/Integration/Pagination/PaginateDirectiveDBTest.php
  tests/Integration/Schema/Directives/AllDirectiveTest.php
  tests/Unit/Schema/Source/SchemaStitcherTest.php
Labels: bug

#2123 Add `@convertEmptyStringsToNull` directive
  CHANGELOG.md
  docs/master/api-reference/directives.md
  src/Schema/Directives/ConvertEmptyStringsToNullDirective.php
  src/lighthouse.php
  tests/Integration/Schema/Directives/ConvertEmptyStringsToNullDirectiveTest.php
  tests/Integration/Schema/Directives/TrimDirectiveTest.php
  tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
  tests/Utils/Mutations/Upload.php
Labels: enhancement

#2125 `RelationDirective`/`batchload_relations` will consider `null` and default connection name the same connection
  CHANGELOG.md
  src/Schema/Directives/RelationDirective.php
  tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
  tests/Utils/Models/NullConnection.php
  tests/database/factories/NullConnectionFactory.php
  tests/database/migrations/2022_04_21_000000_create_testbench_null_connections_table.php
Labels: bug

#2127 Generate classes as `final` through artisan commands
  CHANGELOG.md
  src/Console/stubs/directive.stub
  src/Console/stubs/field_full.stub
  src/Console/stubs/field_simple.stub
  src/Console/stubs/scalar.stub
  src/Console/stubs/subscription.stub
  src/Console/stubs/typeResolver.stub
  src/Console/stubs/validator.stub
  src/Schema/Directives/RelationDirective.php
  tests/Utils/Models/NullConnection.php
Labels: enhancement

#2129 Fix expiring suscriptions docs
  docs/5/subscriptions/getting-started.md
  docs/master/subscriptions/getting-started.md
Labels: docs

#2130 Omit non-nullable arguments in `@convertEmptyStringsToNull`
  CHANGELOG.md
  src/Execution/Arguments/Argument.php
  src/Schema/Directives/ConvertEmptyStringsToNullDirective.php
  tests/Integration/Schema/Directives/ConvertEmptyStringsToNullDirectiveTest.php
Labels: bug

#2115 Discourage nested validators
  docs/5/security/validation.md
  docs/master/security/validation.md
  phpstan.neon
  src/Validation/RulesGatherer.php
  src/Validation/ValidateDirective.php
  tests/Integration/Validation/ValidatorDirectiveTest.php
  tests/Utils/Validators/FooInputValidator.php
Labels: docs
