Repository nuwave/lighthouse, pull requests merged in 2022-06, with the labels that each got.

#2149 Include field that produced a `RateLimitException` in its message
  CHANGELOG.md
  src/Exceptions/RateLimitException.php
  src/Schema/Directives/ThrottleDirective.php
  tests/Integration/Schema/Directives/ThrottleDirectiveTest.php
Labels: enhancement

#2162 Allow customization of determining cache keys
  CHANGELOG.md
  composer.json
  docs/master/performance/caching.md
  src/Cache/CacheDirective.php
  src/Cache/CacheKeyAndTags.php
  src/Cache/CacheKeyAndTagsGenerator.php
  src/Cache/CacheKeyDirective.php
  src/Cache/CacheServiceProvider.php
  src/Cache/ClearCacheDirective.php
  src/Events/StartExecution.php
  src/Schema/Values/TypeValue.php
  tests/Integration/Cache/CacheDirectiveTest.php
  tests/Integration/Cache/ClearCacheDirectiveTest.php
  tests/TestCase.php
Labels: enhancement

#2170 Optimize paginator query when no page info is requested
  CHANGELOG.md
  src/Pagination/ConnectionField.php
  src/Pagination/PaginateDirective.php
  src/Pagination/PaginationArgs.php
  src/Pagination/PaginationManipulator.php
  src/Pagination/PaginationType.php
  src/Pagination/PaginatorField.php
  tests/AssertsQueryCounts.php
  tests/DBTestCase.php
  tests/Integration/Cache/CacheDirectiveTest.php
  tests/Integration/Defer/DeferDBTest.php
  tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
  tests/Integration/Pagination/PaginateDirectiveDBTest.php
  tests/Integration/Schema/Directives/AggregateDirectiveTest.php
  tests/Integration/Schema/Directives/BelongsToDirectiveTest.php
  tests/Integration/Schema/Directives/CountDirectiveDBTest.php
  tests/Integration/Schema/Directives/WithCountDirectiveTest.php
Labels: performance

#2171 Fix TestResponse macros recognition
  CHANGELOG.md
  src/LighthouseServiceProvider.php
Labels: bug
