Repository nuwave/lighthouse, pull requests merged in 2022-12, with the labels that each got.

#2248 Allow interfaces to implement interfaces
  CHANGELOG.md
  src/Schema/TypeRegistry.php
  tests/Unit/Schema/TypeRegistryTest.php
Labels: enhancement

#2252 Avoid duplicated data in relation directives with paginator with non-unique foreign keys
  src/Execution/ModelsLoader/PaginatedModelsLoader.php
  tests/Integration/Schema/Directives/HasManyDirectiveTest.php
  tests/Utils/Models/Post.php
Labels: bug

#2253 Update Adding Directives in extending-lighthouse.md
  docs/5/digging-deeper/extending-lighthouse.md
  docs/master/digging-deeper/extending-lighthouse.md
Labels: docs
