Repository nuwave/lighthouse, pull requests merged in 2022-03, with the labels that each got.

#2043 Add batched federation entity resolvers
  CHANGELOG.md
  docs/5/federation/entities.md
  docs/master/federation/entities.md
  src/Federation/BatchedEntityResolver.php
  src/Federation/EntityResolverProvider.php
  src/Federation/Resolvers/Entities.php
  src/Federation/Types/Any.php
  tests/Integration/Federation/FederationEntitiesTest.php
  tests/Utils/Entities/BatchedFoo.php
Labels: enhancement

#2070 Normalize rules input to ensure Laravel 9 support
  CHANGELOG.md
  src/Validation/RulesGatherer.php
  src/Validation/ValidateDirective.php
  tests/Integration/Validation/ValidatorDirectiveTest.php
  tests/Utils/Validators/RulesWithParametersValidator.php
Labels: bug

#2084 Handle invalid subscriber cache entries from redis
  CHANGELOG.md
  src/Subscriptions/Storage/RedisStorageManager.php
  tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
Labels: bug

#2086 Allow lazy registration of types
  CHANGELOG.md
  docs/5/digging-deeper/adding-types-programmatically.md
  docs/master/digging-deeper/adding-types-programmatically.md
  src/Schema/TypeRegistry.php
  tests/Integration/Schema/Types/InterfaceTest.php
  tests/Integration/Schema/Types/UnionTest.php
  tests/Unit/Schema/TypeRegistryTest.php
Labels: performance

#2088 Register artisan commands not only when running in console
  CHANGELOG.md
  src/LighthouseServiceProvider.php
Labels: enhancement

#2100 Fix definition of `@clearCache` argument `idSource`
  CHANGELOG.md
  docs/5/api-reference/directives.md
  docs/master/api-reference/directives.md
  src/Schema/Directives/ClearCacheDirective.php
  tests/Unit/Subscriptions/Storage/RedisStorageManagerTest.php
Labels: bug

#2093 Annotate generated schema with correct model in paginated relations
  CHANGELOG.md
  docs/5/performance/caching.md
  docs/master/performance/caching.md
  src/Pagination/PaginationManipulator.php
  src/Schema/Directives/BaseDirective.php
  src/Schema/Directives/RelationDirective.php
  tests/Integration/Schema/Directives/HasManyDirectiveTest.php
Labels: bug
