Repository nuwave/lighthouse, pull requests merged in 2023-01, with the labels that each got.

#2277 Fix batch loading a paginated BelongsToMany relation with duplicates
  CHANGELOG.md
  src/Execution/ModelsLoader/PaginatedModelsLoader.php
  tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php
Labels: bug

#2270 BatchLoader fails with expired cache entry
  CHANGELOG.md
  src/Cache/CacheDirective.php
  src/GraphQL.php
  tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
  tests/Integration/Schema/Directives/LimitDirectiveTest.php
Labels: bug

#2234 Add args parameter support for @builder field
  CHANGELOG.md
  UPGRADE.md
  docs/master/api-reference/directives.md
  src/Auth/CanDirective.php
  src/Auth/WhereAuthDirective.php
  src/Execution/Arguments/ArgumentSet.php
  src/Execution/ResolveInfo.php
  src/OrderBy/OrderByDirective.php
  src/Pagination/PaginateDirective.php
  src/Schema/Directives/AggregateDirective.php
  src/Schema/Directives/AllDirective.php
  src/Schema/Directives/BuilderDirective.php
  src/Schema/Directives/CountDirective.php
  src/Schema/Directives/EqDirective.php
  src/Schema/Directives/FindDirective.php
  src/Schema/Directives/FirstDirective.php
  src/Schema/Directives/LikeDirective.php
  src/Schema/Directives/RelationDirective.php
  src/Schema/Directives/RelationDirectiveHelpers.php
  src/Schema/Directives/WithCountDirective.php
  src/Schema/Directives/WithDirective.php
  src/Schema/Directives/WithRelationDirective.php
  src/Support/Contracts/FieldBuilderDirective.php
  src/lighthouse.php
  tests/Integration/Schema/Directives/BuilderDirectiveTest.php
  tests/Integration/Schema/Types/LaravelEnumTypeDBTest.php
  tests/Integration/Schema/Types/PreLaravel9LaravelEnumTypeDBTest.php
  tests/TestCase.php
Labels: enhancement, 6.x

#2176 Pass the path array to `CacheKeyAndTags::key()`
  CHANGELOG.md
  src/Cache/CacheDirective.php
  src/Cache/CacheKeyAndTags.php
  src/Cache/CacheKeyAndTagsGenerator.php
  tests/Integration/Execution/DataLoader/RelationBatchLoaderTest.php
  tests/Integration/Schema/Directives/LimitDirectiveTest.php
Labels: enhancement, 6.x

#2281 Feat: Add support for global id in entity resolver
  CHANGELOG.md
  benchmarks/ASTUnserializationBench.php
  benchmarks/HugeResponseBench.php
  src/Federation/EntityResolverProvider.php
  src/GlobalId/GlobalIdDirective.php
  src/Schema/TypeRegistry.php
  tests/Integration/Federation/FederationEntitiesModelTest.php
Labels: enhancement, 6.x

#2287 Support Laravel 10
  .github/workflows/validate.yml
  CHANGELOG.md
  composer.json
Labels: enhancement
