Repository nuwave/lighthouse, pull requests merged in 2023-08, with the labels that each got.

#2429 `ScoutEnhancer::enhanceBuilder()` improvements to be more similar to …
  CHANGELOG.md
  src/Execution/ResolveInfo.php
  src/Scout/ScoutEnhancer.php
  tests/Unit/Execution/ResolveInfoTest.php
  tests/Unit/Scout/ScoutEnhancerTest.php
Labels: enhancement

#2432 Fix `NOT_LIKE` operator in `@whereConditions`
  CHANGELOG.md
  src/WhereConditions/SQLOperator.php
  tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
Labels: bug

#2428 docs(federation): to categorize information about resolvers
  docs/6/federation/entities.md
  docs/6/federation/entity-representations.md
  docs/6/federation/getting-started.md
  docs/6/federation/reference-resolvers.md
  docs/6/sidebar.js
  docs/master/federation/entities.md
  docs/master/federation/entity-representations.md
  docs/master/federation/getting-started.md
  docs/master/federation/reference-resolvers.md
  docs/master/sidebar.js
Labels: docs
