Repository nuwave/lighthouse, pull requests merged in 2023-02, with the labels that each got.

#2286 Ensure _entities maintains order of representations in result
  CHANGELOG.md
  docs/master/federation/entities.md
  src/Federation/BatchedEntityResolver.php
  src/Federation/EntityResolverProvider.php
  src/Federation/Resolvers/Entities.php
  tests/Integration/Federation/FederationEntitiesTest.php
Labels: bug

#2290 Add validation support for pagination resolver mode
  CHANGELOG.md
  src/Pagination/PaginateDirective.php
  tests/Unit/Pagination/PaginateDirectiveTest.php
Labels: bug

#2276 CanDirective uses the context from GuardDirective
  src/Auth/GuardDirective.php
  src/Schema/Context.php
  src/Support/Contracts/GraphQLContext.php
  tests/TestsSerialization.php
  tests/Unit/Auth/GuardDirectiveTest.php
  tests/Unit/Schema/Execution/Fixtures/FooContext.php
  tests/Unit/Subscriptions/Iterators/AuthenticatingSyncIteratorTest.php
  tests/Utils/Models/Team.php
  tests/Utils/Policies/TeamPolicy.php
Labels: 6.x

#2289 Require filter directives such as `@whereKey` in `@delete`, `@forceDelete` and `@restore`
  CHANGELOG.md
  UPGRADE.md
  docs/master/api-reference/directives.md
  docs/master/eloquent/getting-started.md
  docs/master/eloquent/soft-deleting.md
  src/Schema/Directives/DeleteDirective.php
  src/Schema/Directives/ModifyModelExistenceDirective.php
  src/Schema/Directives/WhereKeyDirective.php
  src/SoftDeletes/ForceDeleteDirective.php
  src/SoftDeletes/RestoreDirective.php
  tests/Integration/Auth/CanDirectiveDBTest.php
  tests/Integration/Schema/Directives/DeleteDirectiveTest.php
  tests/Integration/SoftDeletes/ForceDeleteDirectiveTest.php
  tests/Integration/SoftDeletes/RestoreDirectiveTest.php
Labels: enhancement

#2298 Subscription send only to others
  CHANGELOG.md
  docs/master/subscriptions/filtering-subscriptions.md
  src/Subscriptions/Subscriber.php
  tests/Integration/Subscriptions/Storage/RedisStorageManagerTest.php
Labels: enhancement

#2306 Allow `@where` on fields
  CHANGELOG.md
  docs/master/api-reference/directives.md
  src/Schema/Directives/EqDirective.php
  src/Schema/Directives/WhereDirective.php
  src/Schema/Directives/WhereKeyDirective.php
  tests/Integration/Schema/Directives/WhereDirectiveTest.php
Labels: enhancement

#2310 Fix v6 todos
  .github/workflows/validate.yml
  CHANGELOG.md
  UPGRADE.md
  composer.json
  docs/master/api-reference/directives.md
  src/Console/DirectiveCommand.php
  src/Execution/BatchLoader/RelationBatchLoader.php
  src/Execution/DataLoader/BatchLoader.php
  src/Execution/ModelsLoader/CountModelsLoader.php
  src/Execution/ModelsLoader/PaginatedModelsLoader.php
  src/GraphQL.php
  src/Pagination/PaginateDirective.php
  src/Pagination/PaginationArgs.php
  src/Pagination/PaginationManipulator.php
  src/Schema/Directives/ComplexityDirective.php
  src/Schema/Directives/DeleteDirective.php
  src/Schema/Directives/RelationDirective.php
  src/Schema/Directives/UpsertDirective.php
  src/Schema/Values/FieldValue.php
  src/Subscriptions/Subscriber.php
  src/Subscriptions/SubscriptionRegistry.php
  src/Support/Contracts/ComplexityResolverDirective.php
  src/lighthouse.php
  tests/Integration/Schema/Types/PreLaravel9LaravelEnumTypeDBTest.php
  tests/Integration/WhereConditions/WhereConditionsDirectiveTest.php
  tests/TestCase.php
  tests/Unit/Deprecation/DeprecationTest.php
  tests/Unit/Pagination/PaginateDirectiveTest.php
  tests/Unit/Schema/DirectiveLocatorTest.php
  tests/Unit/Schema/Directives/ComplexityDirectiveTest.php
  tests/Unit/Schema/Directives/Fixtures/Foo.php
  tests/Unit/Schema/Directives/HasManyDirectiveTest.php
  tests/Unit/Schema/Directives/MethodDirectiveTest.php
  tests/Utils/Models/PreLaravel9WithEnum.php
Labels: 6.x

#2304 Require at least one builder enhancement in `@delete`
  docs/master/api-reference/directives.md
  src/Execution/ResolveInfo.php
  src/Schema/Directives/DeleteDirective.php
  src/Schema/Directives/ModifyModelExistenceDirective.php
  src/Schema/Factories/FieldFactory.php
  src/Scout/ScoutEnhancer.php
  tests/Integration/Schema/Directives/DeleteDirectiveTest.php
Labels: enhancement

#1955 Manipulate interfaces
  CHANGELOG.md
  src/Auth/CanDirective.php
  src/OrderBy/OrderByDirective.php
  src/Pagination/PaginateDirective.php
  src/Pagination/PaginationManipulator.php
  src/Schema/AST/ASTBuilder.php
  src/Schema/AST/ASTHelper.php
  src/Schema/Directives/AggregateDirective.php
  src/Schema/Directives/AllDirective.php
  src/Schema/Directives/CountDirective.php
  src/Schema/Directives/DeleteDirective.php
  src/Schema/Directives/EqDirective.php
  src/Schema/Directives/LazyLoadDirective.php
  src/Schema/Directives/LimitDirective.php
  src/Schema/Directives/RelationDirective.php
  src/Schema/Directives/ThrottleDirective.php
  src/Schema/Directives/WhereKeyDirective.php
  src/Schema/Directives/WithCountDirective.php
  src/Schema/Directives/WithDirective.php
  src/SoftDeletes/ForceDeleteDirective.php
  src/SoftDeletes/RestoreDirective.php
  src/SoftDeletes/SoftDeletesDirective.php
  src/Support/Contracts/ArgManipulator.php
  src/Support/Contracts/FieldManipulator.php
  src/Support/Traits/GeneratesColumnsEnum.php
  src/Validation/BaseRulesDirective.php
  src/Validation/ValidatorDirective.php
  src/WhereConditions/WhereConditionsBaseDirective.php
  tests/Integration/Schema/Types/InterfaceTest.php
  tests/Unit/Schema/AST/ASTHelperTest.php
Labels: enhancement, 6.x

#2317 Rework config
  CHANGELOG.md
  docs/master/performance/caching.md
  docs/master/performance/schema-caching.md
  src/Cache/CacheDirective.php
  src/Exceptions/UnknownCacheVersionException.php
  src/LighthouseServiceProvider.php
  src/Schema/AST/ASTCache.php
  src/lighthouse.php
  tests/Console/CacheCommandTest.php
  tests/Console/ClearCacheCommandTest.php
  tests/Integration/Cache/CacheDirectiveTest.php
  tests/Integration/Cache/ClearCacheDirectiveTest.php
  tests/Integration/SchemaCachingTest.php
  tests/TestCase.php
  tests/TestsSchemaCache.php
Labels: enhancement, 6.x

#2318 Add `@api` to mark elements of our public API
  README.md
  src/Execution/ErrorHandler.php
  src/Execution/ValidationRulesProvider.php
  src/GraphQL.php
  src/Schema/Directives/BaseDirective.php
  src/Schema/TypeRegistry.php
  src/Support/Contracts/GraphQLContext.php
  src/Support/Contracts/ProvidesResolver.php
  src/Support/Contracts/ProvidesSubscriptionResolver.php
  src/lighthouse.php
Labels: enhancement, 6.x

#2320 Support Laravel 10
  .github/workflows/validate.yml
  CHANGELOG.md
  benchmarks/ASTUnserializationBench.php
  benchmarks/HugeResponseBench.php
  composer.json
  phpstan.neon
  src/Schema/TypeRegistry.php
  tests/Integration/Validation/RulesDirectiveTest.php
  tests/Integration/Validation/ValidationTest.php
  tests/Integration/Validation/ValidatorDirectiveTest.php
  tests/Unit/Schema/Types/LaravelEnumTypeTest.php
  tests/Utils/Validators/EmailCustomAttributeValidator.php
Labels: enhancement, 5.x
