Repository nuwave/lighthouse, pull requests merged in 2023-03, with the labels that each got.

#2333 Adding routeParams to MakeGraphQLRequests for testing
  CHANGELOG.md
  benchmarks/QueryBench.php
  src/Testing/MakesGraphQLRequests.php
  src/Testing/MakesGraphQLRequestsLumen.php
Labels: enhancement

#2346 chore: cast `schema_cache.enable` to boolean
  src/Schema/AST/ASTCache.php
Labels: bug, 6.x

#2342 Fix empty classnames in definitionExceptions
  CHANGELOG.md
  src/Schema/TypeRegistry.php
  src/Subscriptions/SubscriptionResolverProvider.php
Labels: bug

#2343 Added subscription assertions + docs
  CHANGELOG.md
  _ide_helper.php
  docs/master/testing/phpunit.md
  src/Schema/Context.php
  src/Testing/MakesGraphQLRequests.php
  src/Testing/MakesGraphQLRequestsLumen.php
  src/Testing/TestResponseMixin.php
  tests/Integration/Subscriptions/SubscriptionTest.php
  tests/Unit/Auth/UserContextTest.php
  tests/Utils/Subscriptions/OnPostCreated.php
Labels: enhancement

#2353 Make `Illuminate\Http\Request` optional in `Nuwave\Lighthouse\Support\Contracts\GraphQLContext`
  CHANGELOG.md
  docs/master/api-reference/events.md
  src/Events/EndRequest.php
  src/Events/ManipulateAST.php
  src/Events/StartExecution.php
  src/Events/StartRequest.php
  src/Execution/ContextFactory.php
  src/Schema/HttpGraphQLContext.php
  src/Schema/UserGraphQLContext.php
  src/Subscriptions/Serializer.php
  src/Subscriptions/Storage/CacheStorageManager.php
  src/Support/Contracts/CreatesContext.php
  src/Support/Contracts/GraphQLContext.php
  src/Support/Http/GraphQLController.php
  src/Support/Http/routes.php
  tests/Integration/Subscriptions/SerializerTest.php
  tests/TestsSerialization.php
  tests/Unit/Schema/Execution/CreatesContextTest.php
  tests/Unit/Schema/Execution/Fixtures/FooContext.php
  tests/Unit/Subscriptions/Iterators/IteratorTest.php
  tests/Unit/Subscriptions/SubscriberTest.php
  tests/Unit/Support/Http/Middleware/AttemptAuthenticationTest.php
Labels: enhancement

#2351 Add configurable namespace to allow custom non-root type field resolvers without FQN
  CHANGELOG.md
  docs/master/api-reference/commands.md
  docs/master/api-reference/directives.md
  docs/master/digging-deeper/extending-lighthouse.md
  docs/master/performance/n-plus-one.md
  docs/master/the-basics/fields.md
  rector.php
  src/Console/FieldCommand.php
  src/Console/InterfaceCommand.php
  src/Console/LighthouseGeneratorCommand.php
  src/Console/MutationCommand.php
  src/Console/QueryCommand.php
  src/Console/SubscriptionCommand.php
  src/Console/UnionCommand.php
  src/LighthouseServiceProvider.php
  src/Schema/Directives/ComplexityDirective.php
  src/Schema/Directives/FieldDirective.php
  src/Schema/ResolverProvider.php
  src/Schema/RootType.php
  src/Schema/Values/FieldValue.php
  src/Subscriptions/SubscriptionResolverProvider.php
  src/lighthouse.php
  tests/Integration/Schema/ResolverProviderTest.php
  tests/TestCase.php
  tests/Unit/Schema/Directives/FieldDirectiveTest.php
  tests/Utils/Types/User/NonRootClassResolver.php
Labels: enhancement

#2372 Allow customizing query complexity calculation of `@paginate` with argument `complexityResolver`
  CHANGELOG.md
  Makefile
  docs/4/subscriptions/client-implementations.md
  docs/5/subscriptions/client-implementations.md
  docs/6/subscriptions/client-implementations.md
  docs/master/api-reference/directives.md
  docs/master/subscriptions/client-implementations.md
  src/Pagination/PaginateDirective.php
  tests/Unit/Pagination/PaginateDirectiveTest.php
Labels: enhancement

#2369 Allow dynamically added manipulator directives
  .gitignore
  src/Schema/AST/ASTHelper.php
  tests/Unit/Schema/AST/ASTHelperTest.php
Labels: enhancement
