Repository nuwave/lighthouse, pull requests merged in 2024-06, with the labels that each got.

#2567 Report errors thrown in async mutations
  CHANGELOG.md
  docs/6/api-reference/directives.md
  docs/6/custom-directives/field-directives.md
  docs/6/custom-directives/getting-started.md
  docs/master/api-reference/directives.md
  src/Async/AsyncDirective.php
  src/Async/AsyncMutation.php
  src/Execution/ReportingErrorHandler.php
  src/GraphQL.php
Labels: enhancement

#2570 Eliminate redundant `Model::save()` calls in nested mutations
  CHANGELOG.md
  src/Execution/Arguments/NestedBelongsTo.php
  src/Execution/Arguments/NestedManyToMany.php
  src/Execution/Arguments/NestedMorphTo.php
  src/Execution/Arguments/NestedOneToMany.php
  src/Execution/Arguments/NestedOneToOne.php
  src/Execution/Arguments/SaveModel.php
  src/Schema/Directives/DeleteDirective.php
  src/Schema/Directives/MutationExecutorDirective.php
  tests/Integration/Execution/MutationExecutor/BelongsToTest.php
Labels: bug

#2571 Add option `builder` to `@limit` to apply an actual `LIMIT` clause
  CHANGELOG.md
  docs/6/api-reference/directives.md
  docs/6/custom-directives/input-value-directives.md
  docs/master/api-reference/directives.md
  docs/master/custom-directives/input-value-directives.md
  src/Schema/Directives/LimitDirective.php
  tests/Integration/Auth/CanFindDirectiveDBTest.php
  tests/Integration/Auth/CanQueryDirectiveDBTest.php
  tests/Integration/Auth/CanResolvedDirectiveDBTest.php
  tests/Integration/Execution/MutationExecutor/BelongsToTest.php
  tests/Integration/Schema/Directives/InDirectiveTest.php
  tests/Integration/Schema/Directives/LimitDirectiveTest.php
  tests/Integration/Schema/Directives/NotInDirectiveTest.php
  tests/Integration/Schema/Directives/WhereBetweenDirectiveTest.php
  tests/Integration/Schema/Directives/WhereNotBetweenDirectiveTest.php
  tests/Integration/Schema/Directives/WhereNotNullDirectiveTest.php
  tests/Integration/Schema/Directives/WhereNullDirectiveTest.php
  tests/Unit/Auth/CanModelDirectiveTest.php
  tests/Unit/Auth/CanRootDirectiveTest.php
Labels: enhancement

#2573 Correct decay value calculation in `@throttle` directive
  CHANGELOG.md
  src/Schema/Directives/ThrottleDirective.php
  tests/Integration/Schema/Directives/ThrottleDirectiveTest.php
Labels: bug

#2575 Document adding `SubscriptionRegistry` to `octane.warm`
  docs/6/subscriptions/getting-started.md
  docs/master/subscriptions/getting-started.md
  tests/Integration/Schema/Directives/ThrottleDirectiveTest.php
Labels: docs
